version: "3"
services:
  db:
    container_name: db
    image: mysql:5.7
    platform: linux/amd64
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: database
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: mysqlpassword
      MYSQL_ROOT_PASSWORD: mysqlrootpassword
    healthcheck:
      test: mysqladmin ping --password=mysqlrootpassword
      interval: 10s
      timeout: 2s
      retries: 10
    ports:
      - 3306:3306

  api:
    container_name: codecare
    build: .
    tty: true
    ports:
      - "3000:3000"
      - "3002:3002"
    environment:
      LOG_LEVEL: debug
      DB_HOST: db
      DB_READER_HOST: db
      DB_DATABASE: database
      DB_USERNAME: mysqluser
      DB_PASSWORD: mysqlpassword
      DEBUG: "sequelize:*"
    volumes:
      - ./:/home/node/app:cached
    command: sh -c '
      npm run db:migrate:undo &&
      npm run db:migrate &&
      yarn sequelize-cli db:seed:undo:all &&
      yarn sequelize-cli db:seed:all &&
      npm start'
      # yarn sls config credentials --overwrite --provider aws --key KEY --secret SECRET &&
    depends_on:
      db:
        condition: service_healthy